import type { FestInfo, FestEvent, FoodStall, CampusPin } from './types';

export const FEST_INFO: FestInfo = {
  name: 'Tathva',
  tagline: "South India's largest tech fest",
  startDate: '2026-09-18',
  endDate: '2026-09-20',
  days: [
    { day: 1, label: 'Day 1', date: '2026-09-18' },
    { day: 2, label: 'Day 2', date: '2026-09-19' },
    { day: 3, label: 'Day 3', date: '2026-09-20' },
  ],
};

export const EVENTS: FestEvent[] = [
  // Day 1
  {
    id: 'ev-inaug',
    title: 'Grand Inauguration Ceremony',
    category: 'Pro Show',
    day: 1,
    date: '2026-09-18',
    startTime: '09:30',
    endTime: '11:00',
    venue: 'Open Air Theatre',
    zone: 'Open Air Theatre',
    description:
      'The grand opening of Tathva with chief guest addresses, lamp lighting, and a spectacular drone show. Sets the tone for three days of innovation and celebration.',
    image: 'https://images.pexels.com/photos/13230484/pexels-photo-13230484.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    featured: true,
    tags: ['Opening', 'Drone Show', 'Chief Guest'],
  },
  {
    id: 'ev-robowar',
    title: 'Robo Wars',
    category: 'Technical',
    day: 1,
    date: '2026-09-18',
    startTime: '11:30',
    endTime: '14:00',
    venue: 'NITC Ground',
    zone: 'NITC Ground',
    description:
      'Watch robots battle it out in a steel-cage arena. Teams from across India bring their combat bots to fight for glory. Sparks fly, metal crunches, and only one survives.',
    image: 'https://images.pexels.com/photos/8566536/pexels-photo-8566536.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    featured: true,
    prize: '₹50,000',
    teamSize: '2-5',
    registrationFee: '₹500',
    tags: ['Robotics', 'Combat', 'Engineering'],
  },
  {
    id: 'ev-hack',
    title: 'Hackathon — 24 Hour Code Sprint',
    category: 'Technical',
    day: 1,
    date: '2026-09-18',
    startTime: '12:00',
    endTime: '12:00',
    venue: 'CEDTI Lab',
    zone: 'CEDTI',
    description:
      'A 24-hour coding marathon where teams build solutions to real-world problems. Mentors, free food, caffeine, and prizes worth lakhs await the best builds.',
    image: 'https://images.pexels.com/photos/32778343/pexels-photo-32778343.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    featured: true,
    prize: '₹1,00,000',
    teamSize: '2-4',
    registrationFee: '₹300',
    tags: ['Coding', 'Mentorship', 'Prizes'],
  },
  {
    id: 'ev-ai-workshop',
    title: 'AI & ML Workshop',
    category: 'Workshop',
    day: 1,
    date: '2026-09-18',
    startTime: '14:00',
    endTime: '16:30',
    venue: 'Bhavan A — Seminar Hall',
    zone: 'Bhavan A',
    description:
      'Hands-on workshop on building and deploying machine learning models. From data wrangling to neural networks — learn from industry experts at leading tech companies.',
    image: 'https://images.pexels.com/photos/36522026/pexels-photo-36522026.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    teamSize: 'Solo',
    registrationFee: '₹200',
    tags: ['AI', 'ML', 'Hands-on'],
  },
  {
    id: 'ev-bgmi',
    title: 'BGMI Mobile Tournament',
    category: 'Gaming',
    day: 1,
    date: '2026-09-18',
    startTime: '15:00',
    endTime: '18:00',
    venue: 'SAC Gaming Zone',
    zone: 'SAC',
    description:
      'Battle royale mayhem on mobile. Squad up and fight through 4 maps to be the last team standing. Live commentary and audience screens.',
    image: 'https://images.pexels.com/photos/4218027/pexels-photo-4218027.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prize: '₹30,000',
    teamSize: '4',
    registrationFee: '₹400',
    tags: ['Mobile', 'Battle Royale', 'Esports'],
  },
  {
    id: 'ev-dance1',
    title: 'Footloose — Solo Dance',
    category: 'Dance',
    day: 1,
    date: '2026-09-18',
    startTime: '16:00',
    endTime: '18:30',
    venue: 'Open Air Theatre',
    zone: 'Open Air Theatre',
    description:
      'Solo dance competition where performers bring their best moves across classical, hip-hop, and contemporary styles. The crowd decides the vibe.',
    image: 'https://images.pexels.com/photos/1581906/pexels-photo-1581906.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prize: '₹15,000',
    teamSize: 'Solo',
    registrationFee: '₹150',
    tags: ['Solo', 'Freestyle', 'Crowd Vote'],
  },
  {
    id: 'ev-proshow1',
    title: 'Pro Show Night 1 — DJ Tathva',
    category: 'Pro Show',
    day: 1,
    date: '2026-09-18',
    startTime: '19:00',
    endTime: '22:00',
    venue: 'Open Air Theatre',
    zone: 'Open Air Theatre',
    description:
      'The first night of Tathva goes off with a high-energy DJ set, laser show, and pyrotechnics. The entire campus gathers for the biggest party of the semester.',
    image: 'https://images.pexels.com/photos/5193531/pexels-photo-5193531.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    featured: true,
    tags: ['DJ', 'Laser Show', 'Night'],
  },

  // Day 2
  {
    id: 'ev-expo',
    title: 'NITC Tech Expo',
    category: 'Expo',
    day: 2,
    date: '2026-09-19',
    startTime: '10:00',
    endTime: '17:00',
    venue: 'Main Building Corridor',
    zone: 'Main Building',
    description:
      'A sprawling exhibition of student projects, startup showcases, and cutting-edge tech demos. From self-driving karts to VR experiences, see the future being built today.',
    image: 'https://images.pexels.com/photos/32778343/pexels-photo-32778343.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    featured: true,
    tags: ['Projects', 'Startups', 'Free Entry'],
  },
  {
    id: 'ev-gokart',
    title: 'Go Karting Championship',
    category: 'Sports',
    day: 2,
    date: '2026-09-19',
    startTime: '10:00',
    endTime: '17:00',
    venue: 'Parking Lot Track',
    zone: 'Parking Lot',
    description:
      'A custom-built go-kart track in the parking lot. Race against the clock and other drivers for the fastest lap. Helmets and karts provided.',
    image: 'https://images.pexels.com/photos/5486823/pexels-photo-5486823.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    featured: true,
    prize: '₹20,000',
    teamSize: 'Solo',
    registrationFee: '₹600',
    tags: ['Racing', 'Adrenaline', 'Track'],
  },
  {
    id: 'ev-ctf',
    title: 'Capture The Flag (CTF)',
    category: 'Technical',
    day: 2,
    date: '2026-09-19',
    startTime: '10:30',
    endTime: '14:30',
    venue: 'CEDTI Lab',
    zone: 'CEDTI',
    description:
      'A cybersecurity challenge where teams find hidden flags through reverse engineering, cryptography, and web exploitation. For the hackers and the curious.',
    image: 'https://images.pexels.com/photos/8566536/pexels-photo-8566536.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prize: '₹25,000',
    teamSize: '1-3',
    registrationFee: '₹250',
    tags: ['Security', 'Hacking', 'Crypto'],
  },
  {
    id: 'ev-treasure',
    title: 'Treasure Hunt — Campus Quest',
    category: 'Informal',
    day: 2,
    date: '2026-09-19',
    startTime: '13:00',
    endTime: '16:00',
    venue: 'Starts at Library Lawn',
    zone: 'Library Lawn',
    description:
      'Solve cryptic clues that take you across the entire NITC campus. Teams race against time and each other to find the hidden treasure. Great for first-time visitors to explore campus.',
    image: 'https://images.pexels.com/photos/20200756/pexels-photo-20200756.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prize: '₹10,000',
    teamSize: '2-4',
    registrationFee: '₹200',
    tags: ['Adventure', 'Clues', 'Explore'],
  },
  {
    id: 'ev-valo',
    title: 'Valorant PC Tournament',
    category: 'Gaming',
    day: 2,
    date: '2026-09-19',
    startTime: '14:00',
    endTime: '18:00',
    venue: 'SAC Gaming Zone',
    zone: 'SAC',
    description:
      '5v5 tactical shooter tournament on high-end gaming rigs. Best-of-three elimination brackets. Bring your A-game and your clutch plays.',
    image: 'https://images.pexels.com/photos/4218027/pexels-photo-4218027.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prize: '₹40,000',
    teamSize: '5',
    registrationFee: '₹500',
    tags: ['PC', 'FPS', 'Esports'],
  },
  {
    id: 'ev-groupdance',
    title: 'Rang — Group Dance Competition',
    category: 'Dance',
    day: 2,
    date: '2026-09-19',
    startTime: '16:00',
    endTime: '19:00',
    venue: 'Open Air Theatre',
    zone: 'Open Air Theatre',
    description:
      'Choreographed group performances with stunning formations, props, and storytelling. The flagship dance event of Tathva.',
    image: 'https://images.pexels.com/photos/12327992/pexels-photo-12327992.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    featured: true,
    prize: '₹35,000',
    teamSize: '5-15',
    registrationFee: '₹1000',
    tags: ['Group', 'Choreography', 'Flagship'],
  },
  {
    id: 'ev-proshow2',
    title: 'Pro Show Night 2 — Live Band',
    category: 'Pro Show',
    day: 2,
    date: '2026-09-19',
    startTime: '19:30',
    endTime: '22:00',
    venue: 'Open Air Theatre',
    zone: 'Open Air Theatre',
    description:
      'A live concert by a popular indie band, followed by a fireworks display. The atmosphere is electric as thousands sing along under the stars.',
    image: 'https://images.pexels.com/photos/20993079/pexels-photo-20993079.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    featured: true,
    tags: ['Live Music', 'Band', 'Fireworks'],
  },

  // Day 3
  {
    id: 'ev-bridge',
    title: 'Bridge Design Challenge',
    category: 'Technical',
    day: 3,
    date: '2026-09-20',
    startTime: '10:00',
    endTime: '13:00',
    venue: 'Bhavan B — Workshop Area',
    zone: 'Bhavan B',
    description:
      'Build a load-bearing bridge from popsicle sticks and glue. The bridge that holds the most weight before breaking wins. Engineering meets art.',
    image: 'https://images.pexels.com/photos/36522026/pexels-photo-36522026.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prize: '₹12,000',
    teamSize: '2-3',
    registrationFee: '₹200',
    tags: ['Civil', 'Structural', 'Build'],
  },
  {
    id: 'ev-quiz',
    title: 'Tathva Mega Quiz',
    category: 'Informal',
    day: 3,
    date: '2026-09-20',
    startTime: '11:00',
    endTime: '13:30',
    venue: 'Bhavan A — Seminar Hall',
    zone: 'Bhavan A',
    description:
      'A general knowledge and tech trivia quiz with audio-visual rounds. From ancient history to AI trends — test your wits against the best quizzers on campus.',
    image: 'https://images.pexels.com/photos/20200756/pexels-photo-20200756.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prize: '₹8,000',
    teamSize: '2',
    registrationFee: '₹150',
    tags: ['Trivia', 'Brain', 'Fun'],
  },
  {
    id: 'ev-fifa',
    title: 'FIFA Console Championship',
    category: 'Gaming',
    day: 3,
    date: '2026-09-20',
    startTime: '12:00',
    endTime: '16:00',
    venue: 'SAC Gaming Zone',
    zone: 'SAC',
    description:
      '1v1 FIFA on PlayStation 5. Single elimination. Bring your controller skills and your celebration moves. Winner takes all.',
    image: 'https://images.pexels.com/photos/4218027/pexels-photo-4218027.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prize: '₹15,000',
    teamSize: 'Solo',
    registrationFee: '₹200',
    tags: ['Console', 'Football', '1v1'],
  },
  {
    id: 'ev-photography',
    title: 'Click — Photography Contest',
    category: 'Informal',
    day: 3,
    date: '2026-09-20',
    startTime: '09:00',
    endTime: '15:00',
    venue: 'Library Lawn (Submission)',
    zone: 'Library Lawn',
    description:
      'Capture the spirit of Tathva through your lens. Submit your best 3 photos from the fest. Judges look for emotion, composition, and storytelling.',
    image: 'https://images.pexels.com/photos/5193526/pexels-photo-5193526.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prize: '₹10,000',
    teamSize: 'Solo',
    registrationFee: '₹100',
    tags: ['Photography', 'Creative', 'Open Theme'],
  },
  {
    id: 'ev-closing',
    title: 'Closing Ceremony & Awards',
    category: 'Pro Show',
    day: 3,
    date: '2026-09-20',
    startTime: '17:00',
    endTime: '18:30',
    venue: 'Open Air Theatre',
    zone: 'Open Air Theatre',
    description:
      'The grand finale of Tathva. Award distribution for all event winners, a look back at three incredible days, and the official Tathva after-movie premiere.',
    image: 'https://images.pexels.com/photos/34598092/pexels-photo-34598092.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Awards', 'Finale', 'After-movie'],
  },
  {
    id: 'ev-proshow3',
    title: 'Pro Show Night 3 — Headliner Concert',
    category: 'Pro Show',
    day: 3,
    date: '2026-09-20',
    startTime: '19:00',
    endTime: '22:30',
    venue: 'Open Air Theatre',
    zone: 'Open Air Theatre',
    description:
      'The biggest night of Tathva. A headline performance by a top-tier artist, massive stage production, confetti drops, and an unforgettable close to the fest.',
    image: 'https://images.pexels.com/photos/5193531/pexels-photo-5193531.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    featured: true,
    tags: ['Headliner', 'Concert', 'Finale'],
  },
];

export const FOOD_STALLS: FoodStall[] = [
  {
    id: 'fs-1',
    name: 'Kerala Kitchen',
    cuisine: 'Kerala Traditional',
    zone: 'Library Lawn',
    location: 'Near Library Lawn — Stall A1',
    rating: 4.8,
    priceRange: '₹40-120',
    specialties: ['Sadya Meals', 'Appam & Stew', 'Puttu & Kadala'],
    openHours: '8:00 AM — 10:00 PM',
    image: 'https://images.pexels.com/photos/32448263/pexels-photo-32448263.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    veg: true,
  },
  {
    id: 'fs-2',
    name: 'Biryani Blues',
    cuisine: 'Hyderabadi',
    zone: 'Library Lawn',
    location: 'Near Library Lawn — Stall A2',
    rating: 4.6,
    priceRange: '₹80-200',
    specialties: ['Chicken Biryani', 'Veg Biryani', 'Raita & Salan'],
    openHours: '11:00 AM — 11:00 PM',
    image: 'https://images.pexels.com/photos/30174573/pexels-photo-30174573.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    veg: false,
  },
  {
    id: 'fs-3',
    name: 'Street Wok',
    cuisine: 'Indo-Chinese',
    zone: 'SAC',
    location: 'SAC Food Court — Stall B1',
    rating: 4.5,
    priceRange: '₹60-150',
    specialties: ['Hakka Noodles', 'Chilli Chicken', 'Manchurian'],
    openHours: '12:00 PM — 10:00 PM',
    image: 'https://images.pexels.com/photos/38443570/pexels-photo-38443570.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    veg: false,
  },
  {
    id: 'fs-4',
    name: 'Dosa Junction',
    cuisine: 'South Indian',
    zone: 'SAC',
    location: 'SAC Food Court — Stall B2',
    rating: 4.7,
    priceRange: '₹30-90',
    specialties: ['Masala Dosa', 'Idli Sambar', 'Filter Coffee'],
    openHours: '7:00 AM — 10:00 PM',
    image: 'https://images.pexels.com/photos/32448263/pexels-photo-32448263.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    veg: true,
  },
  {
    id: 'fs-5',
    name: 'Shawarma Hub',
    cuisine: 'Arabian',
    zone: 'NITC Ground',
    location: 'NITC Ground — Stall C1',
    rating: 4.4,
    priceRange: '₹50-130',
    specialties: ['Chicken Shawarma', 'Grilled Wrap', 'Falafel'],
    openHours: '4:00 PM — 1:00 AM',
    image: 'https://images.pexels.com/photos/30174573/pexels-photo-30174573.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    veg: false,
  },
  {
    id: 'fs-6',
    name: 'Chai & Chill',
    cuisine: 'Beverages & Snacks',
    zone: 'Library Lawn',
    location: 'Library Lawn — Stall A3',
    rating: 4.3,
    priceRange: '₹20-80',
    specialties: ['Masala Chai', 'Pakora', 'Maggi Special'],
    openHours: '8:00 AM — 2:00 AM',
    image: 'https://images.pexels.com/photos/38443570/pexels-photo-38443570.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    veg: true,
  },
  {
    id: 'fs-7',
    name: 'Pizza Point',
    cuisine: 'Italian',
    zone: 'SAC',
    location: 'SAC Food Court — Stall B3',
    rating: 4.2,
    priceRange: '₹100-300',
    specialties: ['Margherita', 'Pepperoni', 'Garlic Bread'],
    openHours: '11:00 AM — 11:00 PM',
    image: 'https://images.pexels.com/photos/30174573/pexels-photo-30174573.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    veg: false,
  },
  {
    id: 'fs-8',
    name: 'Ice Cream Island',
    cuisine: 'Desserts',
    zone: 'NITC Ground',
    location: 'NITC Ground — Stall C2',
    rating: 4.6,
    priceRange: '₹30-120',
    specialties: ['Kulfi Falooda', 'Gelato', 'Sundae Special'],
    openHours: '10:00 AM — 11:00 PM',
    image: 'https://images.pexels.com/photos/38443570/pexels-photo-38443570.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    veg: true,
  },
];

export const CAMPUS_PINS: CampusPin[] = [
  { id: 'pin-oat', name: 'Open Air Theatre', type: 'stage', zone: 'Open Air Theatre', x: 50, y: 35, description: 'Main stage for pro shows, dance events, and ceremonies' },
  { id: 'pin-ground', name: 'NITC Ground', type: 'event', zone: 'NITC Ground', x: 72, y: 58, description: 'Robo Wars, sports events, and food stalls' },
  { id: 'pin-sac', name: 'Student Activity Centre', type: 'game', zone: 'SAC', x: 30, y: 50, description: 'Gaming tournaments and food court' },
  { id: 'pin-cedti', name: 'CEDTI Lab', type: 'event', zone: 'CEDTI', x: 60, y: 72, description: 'Hackathon and CTF competitions' },
  { id: 'pin-bhavanA', name: 'Bhavan A', type: 'event', zone: 'Bhavan A', x: 40, y: 65, description: 'Workshops, seminars, and quiz events' },
  { id: 'pin-bhavanB', name: 'Bhavan B', type: 'event', zone: 'Bhavan B', x: 55, y: 80, description: 'Build competitions and workshops' },
  { id: 'pin-library', name: 'Library Lawn', type: 'food', zone: 'Library Lawn', x: 25, y: 30, description: 'Food stalls, chai, and treasure hunt start' },
  { id: 'pin-main', name: 'Main Building', type: 'event', zone: 'Main Building', x: 48, y: 50, description: 'Tech Expo and registration desk' },
  { id: 'pin-parking', name: 'Parking Lot Track', type: 'event', zone: 'Parking Lot', x: 82, y: 82, description: 'Go karting track' },
  { id: 'pin-info', name: 'Info Desk', type: 'info', zone: 'Main Building', x: 45, y: 55, description: 'Help desk, maps, and lost & found' },
];

export const CATEGORY_META: Record<string, { color: string; bg: string; border: string; label: string }> = {
  Technical: { color: 'text-brand-300', bg: 'bg-brand-500/15', border: 'border-brand-500/30', label: 'Technical' },
  Gaming: { color: 'text-accent-300', bg: 'bg-accent-500/15', border: 'border-accent-500/30', label: 'Gaming' },
  Informal: { color: 'text-gold-400', bg: 'bg-gold-500/15', border: 'border-gold-500/30', label: 'Informal' },
  Dance: { color: 'text-pink-300', bg: 'bg-pink-500/15', border: 'border-pink-500/30', label: 'Dance' },
  'Pro Show': { color: 'text-purple-300', bg: 'bg-purple-500/15', border: 'border-purple-500/30', label: 'Pro Show' },
  Workshop: { color: 'text-cyan-300', bg: 'bg-cyan-500/15', border: 'border-cyan-500/30', label: 'Workshop' },
  Expo: { color: 'text-teal-300', bg: 'bg-teal-500/15', border: 'border-teal-500/30', label: 'Expo' },
  Sports: { color: 'text-red-300', bg: 'bg-red-500/15', border: 'border-red-500/30', label: 'Sports' },
};
